dataset:
  name: "celebrity_personalities"
  size: "1000+"
  source: "youtube_videos"
  
  splits:
    train: 0.7
    validation: 0.15
    test: 0.15
    
  celebrities:
    min_videos_per_celebrity: 3
    story_extraction_required: true
    
validation:
  celebrity_split_validation: true
  cross_validation_folds: 5
  ablation_test_removal_pct: 0.10