validation_strategies:
  celebrity_based_splitting:
    description: "Same celebrity never in train/test"
    enabled: true
    
  cross_validation:
    description: "Train on 80% celebrities, test on different 20%"
    folds: 5
    enabled: true
    
  ablation_test:
    description: "Remove 10% training celebrities, check accuracy drop"
    removal_percentage: 0.10
    enabled: true
    
thresholds:
  max_accuracy_drop: 0.05
  variance_threshold: 0.15
  class_imbalance_threshold: 0.10