api:
  key: "f38d44bfe4ae7c915e2be3ec32c2101f"
  client_id: "10000127"
  base_url: "https://api.behavioralsignals.com"
  
timeouts:
  api_submission: 120       # 2 minutes
  api_check_interval: 5     # 5 seconds
  max_wait: 600            # 10 minutes
  
paths:
  # Shared data directory paths (processed by xenodex_fulfillment)
  shared_converted: "/home/Mike/projects/xenodex/xenodex_fulfillment/data/converted"  # MP3 files from xenodex_fulfillment processing
  shared_samples: "/home/Mike/projects/xenodex/xenodex_fulfillment/data/samples"      # Sample files from xenodx_fulfillment processing  
  shared_chunks: "/home/Mike/projects/xenodex/xenodex_fulfillment/data/chunks"        # Chunk files from xenodx_fulfillment processing
  
  # API-specific result paths
  results: "./results"
  reports: "../../reports/behavior_signals"
  jobs: "../data/jobs"