name: "ensemble"
description: "Combined F/T and Di/De detector ensemble"

ensemble:
  detectors:
    - f_t_detector
    - di_de_detector
  
  combination_strategy: "weighted_average"
  weights:
    f_t_detector: 0.5
    di_de_detector: 0.5

validation:
  cost_estimate: 50-75
  target_accuracy: 0.90
  
system:
  total_cost_threshold: 369.0
  total_time_threshold: 80.0