name: "f_t_detector"
description: "Feeler/Thinker personality detector"

model:
  base_model: "gpt-4o-mini"
  temperature: 0.1
  max_tokens: 1
  
training:
  iterations:
    - target_accuracy: 0.80
      cost_estimate: 6-12
      time_hours: 3-6
    - target_accuracy: 0.90
      cost_estimate: 12-24
      time_hours: 6-12
    - target_accuracy: 0.95
      cost_estimate: 12-24
      time_hours: 6-12

validation:
  overfitting_tests:
    - celebrity_splitting
    - cross_validation
    - ablation_test
  accuracy_drop_threshold: 0.05
  
plateau_detection:
  min_improvement: 0.02
  max_iterations: 3
  max_cost: 100.0