# Hume AI Configuration

# API credentials and endpoints
api:
  key: "${HUME_API_KEY}"  # Use environment variables in production
  client_id: "${HUME_CLIENT_ID}"
  base_url: "https://api.hume.ai"
  version: "v0"
  
# API-specific timeouts (in seconds)
timeouts:
  api_submission: 120       # Time to wait for submission response
  api_check_interval: 5     # Interval between status checks
  max_wait: 600            # Maximum time to wait for completion
  connection_timeout: 30    # Connection timeout
  read_timeout: 60         # Read timeout
  
# Path configuration
paths:
  # Shared data directory paths (absolute paths to shared data)
  shared_converted: "/home/Mike/projects/xenodex/xenodx_fulfillment/data/converted"
  shared_samples: "/home/Mike/projects/xenodex/xenodx_fulfillment/data/samples"
  shared_chunks: "/home/Mike/projects/xenodex/xenodx_fulfillment/data/chunks"
  
  # API-specific paths (relative to API directory)
  results: "./results"                    # Store results within API directory
  reports: "../../reports/hume_ai"        # Reports at top level for easy access
  jobs: "../../data/jobs"                 # Shared job tracking
  
# Processing configuration
processing:
  supported_formats: ["mp3", "wav", "m4a", "flac", "ogg", "aac"]
  max_file_size: 10485760  # 10MB in bytes
  default_sample_rate: 16000
  chunk_duration: 120      # Duration in seconds for chunking
  min_chunk_duration: 30   # Minimum chunk size
  
# Feature flags
features:
  enable_chunking: true
  enable_batch_processing: true
  enable_retry: true
  enable_caching: true
  max_retries: 3
  
# API-specific settings for Hume AI
settings:
  models: ["prosody", "language", "face"]  # Available models
  granularity: "utterance"                 # or "conversational"
  window:
    length: 4.0
    step: 0.5
  language: "en"